sudo: required
services:
  - docker

before_install:
  - docker build -t rockman25/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rockman25/react-test npm test -- --coverage

after_success:
  - docker build -t rockman25/multi-client ./client
  - docker build -t rockman25/multi-nginx ./nginx
  - docker build -t rockman25/multi-server ./server
  - docker build -t rockman25/multi-worker ./worker
  # Log into to docker CLI
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push rockman25/multi-client
  - docker push rockman25/multi-nginx
  - docker push rockman25/multi-server
  - docker push rockman25/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  environment: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-789458539685
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
